CREATE TABLE IF NOT EXISTS Script (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  nativeName TEXT NOT NULL,
  verifiedUnicodeSample TEXT,
  fallbackGlyphAsset TEXT NOT NULL,
  family TEXT NOT NULL,
  parentId TEXT,
  region TEXT NOT NULL,
  eraStart INTEGER,
  eraEnd INTEGER,
  direction TEXT NOT NULL,
  verificationStatus TEXT NOT NULL DEFAULT 'UNVERIFIED',
  publishStatus TEXT NOT NULL DEFAULT 'DRAFT',
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (parentId) REFERENCES Script(id)
);

CREATE TABLE IF NOT EXISTS ScriptSource (
  id TEXT PRIMARY KEY,
  scriptId TEXT NOT NULL,
  label TEXT NOT NULL,
  url TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (scriptId) REFERENCES Script(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Product (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  productType TEXT NOT NULL,
  scriptId TEXT,
  publishStatus TEXT NOT NULL DEFAULT 'DRAFT',
  isPaid INTEGER NOT NULL DEFAULT 1,
  priceInPaise INTEGER NOT NULL,
  currency TEXT NOT NULL DEFAULT 'INR',
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (scriptId) REFERENCES Script(id)
);

CREATE TABLE IF NOT EXISTS SKU (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  productId TEXT NOT NULL,
  publishStatus TEXT NOT NULL DEFAULT 'DRAFT',
  isActive INTEGER NOT NULL DEFAULT 0,
  orderItemsJson TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (productId) REFERENCES Product(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Bundle (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  publishStatus TEXT NOT NULL DEFAULT 'DRAFT',
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS OrderRecord (
  id TEXT PRIMARY KEY,
  userId TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING_PAYMENT',
  amountInPaise INTEGER NOT NULL,
  currency TEXT NOT NULL DEFAULT 'INR',
  razorpayOrderId TEXT UNIQUE,
  itemsJson TEXT NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Payment (
  id TEXT PRIMARY KEY,
  orderId TEXT NOT NULL,
  provider TEXT NOT NULL,
  providerPaymentId TEXT,
  providerOrderId TEXT,
  status TEXT NOT NULL DEFAULT 'CREATED',
  signatureVerified INTEGER NOT NULL DEFAULT 0,
  rawEventJson TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (orderId) REFERENCES OrderRecord(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UserAccess (
  id TEXT PRIMARY KEY,
  userId TEXT NOT NULL,
  productId TEXT NOT NULL,
  orderId TEXT NOT NULL,
  grantedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(userId, productId),
  FOREIGN KEY (productId) REFERENCES Product(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AdminApproval (
  id TEXT PRIMARY KEY,
  skuId TEXT NOT NULL,
  status TEXT NOT NULL,
  actorId TEXT NOT NULL,
  note TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (skuId) REFERENCES SKU(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SpineEvent (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  actorId TEXT,
  subjectId TEXT,
  payloadJson TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SpineJob (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  attempts INTEGER NOT NULL DEFAULT 0,
  payloadJson TEXT,
  lastError TEXT,
  runAfter TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SpineAuditLog (
  id TEXT PRIMARY KEY,
  eventType TEXT NOT NULL,
  actorId TEXT,
  subjectId TEXT,
  payloadJson TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
